@startuml Desk Controller v1.0.0

title Desk Controller v1.0.0

node "Desk-Controller [i.e. Raspberry Pi]" {
	node "UI" {
		[System Monitor]
	}

	node "Backend" {
		[Config Reader Service]
		[System Monitor Server]
	}
	
	[System Monitor] --> [System Monitor Server]
	[System Monitor Server] --> Socket
}

node "Monitored PC" {
	node "Backend app" {
		Socket <-- [System-Monitor-Client]
	}
}

folder "\~/.desk-controller" {
	[Config]

	note top of Config
		Data about monitored PCs
	end note

}

[Config Reader Service] --> [Config]

@enduml 

